from baseGame import betTimes, win, coinTotal,meter,bonusBaseMoney,bonusEnhanceStatus_1,bonusEnhanceStatus_2,bonusEnhanceStatus_3,bonusEnhanceStatus_4,bonusEnhanceStatus_5

print(betTimes, win, coinTotal,meter,bonusBaseMoney,bonusEnhanceStatus_1,bonusEnhanceStatus_2,bonusEnhanceStatus_3,bonusEnhanceStatus_4,bonusEnhanceStatus_5)